language: C

compiler:
  - gcc
 
before_script:
  - mkdir build
  - mkdir headers
  - cd lib
  - ls
  - cd ../build
  - cmake ..
  
script: 
  - make
  - make test
  - sudo make install
  
after_script:
 - cd ../lib
 - ls
 - cd ..
 - ls
 - runSistema.sh
