language: C

compiler:
  - gcc
 
before_script:
  - mkdir build
  - cd build
  - cmake ..
  
script: 
  - make
  - sudo make install

after_script:
  - cd bin
  - ./hello
  - cd ../../../../../..
  - /usr/local/bin/runHello.sh
