language: C

compiler:
  - gcc
 
before_script:
  - mkdir build
  - cd build
  - cmake ..
  
script: 
  - make
  - sudo make install

after_sucess: 
  - cd ../../../../..
  - cd /usr/local/bin/runHello.sh
